# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8455e547e80e42fa4684f24c997b04b08c31d2a555687239e429857a379061961ed60cd1a473aa69d4f7663a4b4d9c96a0cd560e297fccd5322def743505f2e4

test:
  secret_key_base: 5631a9dc050e2cfac0a61c0f97091ca43c451fbaf05aa3d67501dbce1d0e2e9bd2ff79be9cf3b8a8bcb05d02864760629a276b67eec26bbada2e0a541d1b717d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
